# Welcome to Jekyll!
#
# Site settings
title: GitHub Pages Boilerplate
email: phobetron@gmail.com
github_username:  phobetron
description: >-
  This is an example Jekyll site, with Webpack and Vue support, for publishing on GitHub
baseurl: "/ghp-boilerplate"
url: "https://charleshudson.com"

# Serve settings
host: "0.0.0.0"
port: 8080

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
plugins:
  - github-pages
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - webpack.config.js
  - app/
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
