# Welcome to Jekyll!
#
# Site settings
title: Charles Hudson
email: work@charleshudson.com
github_username:  phobetron
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://charleshudson.com"

# Serve settings
host: "0.0.0.0"
port: 8080

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - webpack.config.js
  - app/
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
